# Generated by Django 4.2.11 on 2024-04-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zapchast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=250)),
                ('name_ru', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='zapchast')),
            ],
        ),
    ]
