# Generated by Django 4.2.11 on 2024-04-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyixa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=250)),
                ('name_ru', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('description_ru', models.TextField()),
                ('price', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=100)),
                ('zapchast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyixa.zapchast')),
            ],
        ),
    ]
